[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "oemof-tabular-plugins"
authors = [
  { name="Ciara Dunks", email="ciara.dunks@rl-institut.de" },
  { name="Pierre-François Duc", email="pierre-francois.duc@rl-institut.de" },
]
description = "A package that contains various constraint facades to be used with oemof-tabular"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
version = "0.1.0"
dynamic = ["dependencies", "readme"]

[tool.setuptools.dynamic]
readme = {file = ["README.rst"]}
version = {attr = "oemof_tabular_plugins.version"}
dependencies = {file = ["requirements/build_requirements.txt"]}

[project.scripts]
dp_to_json = "oemof_tabular_plugins.datapackage.dp_to_json:main"
json_to_dp = "oemof_tabular_plugins.datapackage.json_to_dp:main"

[project.urls]
Homepage = "https://github.com/rl-institut/oemof-tabular-plugins"
Issues = "https://github.com/rl-institut/oemof-tabular-plugins/issues"
