"""
Code generated by ChatGPT 5.0 and adapted
"""

#!/usr/bin/env python3
import argparse
import json
import csv
import sys
from pathlib import Path
from typing import Dict, Any, List, Union


def resource_paths(package_dir: Path, resource: Dict[str, Any]) -> List[Path]:
    p = resource.get("path")
    if p is None:
        raise ValueError(f"Resource {resource.get('name', '<unnamed>')} has no 'path'")
    if isinstance(p, str):
        p_list = [p]
    elif isinstance(p, list):
        p_list = p
    else:
        raise TypeError("'path' must be string or list of strings")
    paths: List[Path] = []
    for rel in p_list:
        candidate = (package_dir / rel).resolve()
        # prevent escaping the package dir
        if not str(candidate).startswith(str(package_dir.resolve())):
            raise ValueError(f"Unsafe path for resource {resource.get('name')}: {rel}")
        paths.append(candidate)
    return paths


def csv_reader_for_resource(
    fp, resource: Dict[str, Any], *, force_schema_headers: bool = False
):
    dialect = resource.get("dialect", {}) or {}
    delimiter = dialect.get("delimiter", ";")
    quotechar = dialect.get("quoteChar") or dialect.get("quotechar") or '"'
    doublequote = dialect.get("doubleQuote") if "doubleQuote" in dialect else True
    escapechar = dialect.get("escapeChar") or None

    # If schema defines fields and we force schema headers, use them
    fieldnames = None
    if force_schema_headers:
        schema = resource.get("schema") or {}
        if isinstance(schema, dict):
            fields = schema.get("fields") or []
            if fields and all(isinstance(f, dict) and "name" in f for f in fields):
                fieldnames = [f["name"] for f in fields]

    if fieldnames is not None:
        return csv.DictReader(
            fp,
            delimiter=delimiter,
            quotechar=quotechar,
            doublequote=doublequote,
            escapechar=escapechar,
            fieldnames=fieldnames,
        )
    else:
        return csv.DictReader(
            fp,
            delimiter=delimiter,
            quotechar=quotechar,
            doublequote=doublequote,
            escapechar=escapechar,
        )


def export_single_json(
    package_dir: Path, out_dir: Path, *, no_headers: bool = False
) -> Dict[str, Any]:
    """
    Export a Frictionless Data Package (CSV resources) into a single JSON file.

    This collects all rows from each CSV resource listed in ``pkg['resources']`` and
    writes a single JSON document with two top-level keys:

    - ``"metadata"``: the original ``datapackage.json`` content (``pkg`` as provided)
    - ``"data"``: a mapping of ``{resource_name: [row, row, ...]}`` where each row is a
      dict produced by ``csv.DictReader``

    If a resource’s ``path`` is a list (multi-file resource), rows from all files are
    concatenated into the same list for that resource.

    Parameters
    ----------
    package_dir : pathlib.Path
        Directory containing ``datapackage.json`` and the resource files referenced by it.
    out_dir : pathlib.Path
        Destination directory; will be created if it does not exist.
    no_headers : bool, optional
        If True, treat CSVs as lacking a header row and use field names from
        ``resource.schema.fields[*].name`` (when available). If False (default),
        header is taken from the first line of each CSV.

    Returns
    -------
    Dict[str, str]
        A dict with key ``"output"`` pointing to the absolute path of the written file
        (``datapackage_export.json`` inside ``out_dir``).

    Notes
    -----
    - CSV reading respects per-resource options if present:
      ``resource.encoding`` and basic dialect fields in ``resource.dialect`` such as
      ``delimiter``, ``quoteChar``/``quotechar``, ``doubleQuote``, and ``escapeChar``.
    - All JSON is written as UTF-8, with ``ensure_ascii=False`` and pretty indentation.
    - This function loads all rows into memory; for very large datasets consider using
      an NDJSON/streaming export instead.

    Raises
    ------
    FileNotFoundError
        If any referenced resource file does not exist.
    ValueError, TypeError
        If a resource has an invalid ``path`` definition or unsafe path resolution.
    UnicodeDecodeError
        If a file cannot be decoded with the specified encoding.
    csv.Error
        If the CSV is malformed.
    OSError
        For general I/O errors while reading or writing files.

    Examples
    --------
    >>> from pathlib import Path
    >>> import json
    >>> pkg = json.loads(Path("my_pkg/datapackage.json").read_text(encoding="utf-8"))
    >>> export_single_json(Path("my_pkg"), Path("out"))
    {'output': '/abs/path/out/datapackage_export.json'}
    """

    dp_path = package_dir / "datapackage.json"
    if not dp_path.exists():
        raise FileNotFoundError(f"datapackage.json not found in {package_dir}")
    with dp_path.open("r", encoding="utf-8") as f:
        pkg = json.load(f)

    out_dir.mkdir(parents=True, exist_ok=True)
    data: Dict[str, List[Dict[str, Any]]] = {}
    resources = pkg.get("resources") or []
    for res in resources:
        name = res.get("name") or (
            Path(
                res.get("path") if isinstance(res.get("path"), str) else "resource"
            ).stem
        )
        rows: List[Dict[str, Any]] = []
        paths = resource_paths(package_dir, res)
        for p in paths:
            encoding = res.get("encoding", "utf-8")
            with p.open("r", encoding=encoding, newline="") as inf:
                reader = csv_reader_for_resource(
                    inf, res, force_schema_headers=no_headers
                )
                for row in reader:
                    rows.append({str(k): v for k, v in row.items()})
        data[name] = rows
    output_path = out_dir / "datapackage_export.json"
    with output_path.open("w", encoding="utf-8") as out:
        json.dump({"metadata": pkg, "data": data}, out, ensure_ascii=False, indent=4)
    return str(output_path)


def main():
    parser = argparse.ArgumentParser(
        description="Export a Frictionless Data Package (CSV resources) to JSON."
    )
    parser.add_argument(
        "package_dir", help="Path to folder that contains datapackage.json"
    )
    parser.add_argument("--out", "-o", default=".", help="Output folder (default: .)")
    args = parser.parse_args()

    package_dir = Path(args.package_dir).expanduser().resolve()
    out_dir = Path(args.out).expanduser().resolve()

    fpath = export_single_json(package_dir, out_dir)
    print(f"Datapackage exported to JSON into the file '{fpath}'")


if __name__ == "__main__":
    main()
