"""
Code generated by ChatGPT 5.0 and adapted
"""

#!/usr/bin/env python3
import argparse
import csv
import json
from pathlib import Path
from typing import Dict, Any, List, Union


def ensure_dir(p: Path) -> None:
    p.mkdir(parents=True, exist_ok=True)


def safe_join(base: Path, rel: Union[str, Path]) -> Path:
    """
    Join base with rel and ensure the result stays within base.
    """
    target = (base / rel).resolve()
    if not str(target).startswith(str(base.resolve())):
        raise ValueError(f"Unsafe path outside output directory: {rel}")
    return target


def get_schema_fieldnames(
    res: Dict[str, Any], sample_rows: List[Dict[str, Any]]
) -> List[str]:
    schema = res.get("schema")
    if isinstance(schema, dict):
        fields = schema.get("fields") or []
        if fields and all(isinstance(f, dict) and "name" in f for f in fields):
            return [f["name"] for f in fields]
    # Fallback to keys from the first row
    if sample_rows:
        return list(sample_rows[0].keys())
    return []


def dialect_from_resource(res: Dict[str, Any]) -> Dict[str, Any]:
    d = (res.get("dialect") or {}) if isinstance(res.get("dialect"), dict) else {}
    return {
        "delimiter": d.get("delimiter", ";"),
        "quotechar": d.get("quoteChar", d.get("quotechar", '"')),
        "doublequote": d.get("doubleQuote", True),
        "escapechar": d.get("escapeChar", "\n"),
    }


def write_csv(
    rows: List[Dict[str, Any]],
    out_csv: Path,
    fieldnames: List[str],
    res_meta: Dict[str, Any],
) -> int:
    d = dialect_from_resource(res_meta)
    count = 0
    ensure_dir(out_csv.parent)
    with out_csv.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=fieldnames,
            delimiter=d["delimiter"],
            quotechar=d["quotechar"],
            doublequote=d["doublequote"],
            escapechar=d["escapechar"],
        )
        writer.writeheader()
        for row in rows:
            # normalize: ensure all headers exist; stringify keys
            r = {str(k): row.get(k, "") for k in fieldnames}
            writer.writerow(r)
            count += 1
    return count


def rebuild_single_json(
    dp_dict: Dict, out_dir: Path, *, overwrite: bool = False
) -> Dict[str, Any]:

    dp_metadata = dp_dict.get("metadata") or {}
    dp_resources = dp_dict.get("data") or {}

    if not dp_metadata or "resources" not in dp_metadata:
        raise ValueError("Invalid single-JSON export: missing 'metadata.resources'")

    resources = dp_metadata.get("resources") or []

    updated_resources = []

    for res in resources:

        name = res.get("name") or "resource"
        res["dialect"] = dialect_from_resource(res)
        rows = dp_resources.get(name, [])
        path_spec = res.get("path")

        # Determine output strategy based on path type
        if isinstance(path_spec, list):
            if not path_spec:
                raise ValueError(f"Resource '{name}' has empty path list")
            # Use the first path as the write target and collapse to single-file
            target_rel = path_spec[0]
            res["path"] = target_rel  # collapse in metadata for consistency
        elif isinstance(path_spec, str):
            target_rel = path_spec
        else:
            # No path in metadata; fallback to data/<name>.csv
            target_rel = str(Path("data") / f"{name}.csv")
            res["path"] = target_rel

        out_csv = safe_join(out_dir, target_rel)

        if out_csv.exists() and not overwrite:
            raise FileExistsError(f"{out_csv} exists (pass --overwrite to replace)")

        headers = get_schema_fieldnames(res, rows)
        write_csv(rows, out_csv, headers, res)

        # Ensure encoding is set to utf-8 in metadata
        res["encoding"] = "utf-8"
        updated_resources.append(res)

    # Write datapackage.json with updated paths/encodings
    ensure_dir(out_dir)
    dp_out = out_dir / "datapackage.json"

    dp_metadata["resources"] = updated_resources

    with dp_out.open("w", encoding="utf-8") as f:
        json.dump(dp_metadata, f, ensure_ascii=False, indent=4)

    return out_dir


def main():
    ap = argparse.ArgumentParser(
        description="Rebuild a Frictionless Data Package from a single JSON export, preserving original folder structure."
    )
    ap.add_argument("single_json", help="Path to datapackage in JSON format")
    ap.add_argument("--out", "-o", default=".", help="Output folder (default: .)")
    ap.add_argument("--overwrite", action="store_true", help="Overwrite existing files")
    args = ap.parse_args()

    src = Path(args.single_json).expanduser().resolve()
    out_dir = Path(args.out).expanduser().resolve()
    with src.open("r", encoding="utf-8") as f:
        json_dp = json.load(f)
    result = rebuild_single_json(json_dp, out_dir, overwrite=args.overwrite)
    print(f"Datapackage saved under '{result}'")


if __name__ == "__main__":
    main()
    # import os
    # def to_abs_path(s: str) -> Path:
    #     # expand env vars and ~, then make absolute without requiring the path to exist
    #     p = Path(os.path.expandvars(s)).expanduser()
    #     return p.resolve(strict=False)  # absolute, normalized
    #
    # src=to_abs_path("/home/pierre-francois/Documents/repos/oemof-tabular-plugins/export") / "datapackage_export.json"
    # out_dir = to_abs_path("~/Documents/repos/oemof-tabular-plugins/examples/scenarios/arusi_light2")
    # rebuild_single_json(src, out_dir, overwrite=True)
