from oemof_tabular_plugins.wefe.constraints.constraint_facades import (
    CONSTRAINT_TYPE_MAP,
)
from oemof.tabular.facades import TYPEMAP

from oemof.tabular.facades import Volatile
from oemof_tabular_plugins.wefe.facades import MIMO_ReverseOsmosis, MIMO_UltraFiltration, MIMO_NanoFiltration, \
    MIMO_MicroFiltration, MIMO_BioFiltration
from oemof_tabular_plugins.wefe.facades.mimo_ed import MIMO_Electrodialysis
from oemof_tabular_plugins.wefe.facades.mimo_ix import MIMO_IonExchange

from .facades import (
    PVPanel,
    WindTurbine,
    MIMO,
    APV,
    MimoCrop,
    SimpleCrop,
    WaterPump,
    WaterFiltration,
    Inverter,
    RRHydropower,
    ReverseOsmosis,
    UltraFiltration,
    NanoFiltration,
    MicroFiltration,
    BioFiltration,
    ActivatedCarbonFilter,
    CeramicFilter,
    CartridgeFilter,
    SlowSandFilter,
    ElectrodialysisUnit,
    IonExchange,
    UVDisinfection,
    Boiling,
    Distillation,
    MembraneDistillation,
    Ozonation,
    PhotocatalyticUnit,
    BiologicalDenitrification,
    Adsorption,
    CoagulationFlocculation,
    Chlorination,
    SimpleOxidation,
    IntakeStructure,
    CoarseBarScreen,
    FineScreen,
    GritChamber,
    WaterReuseSystem,
    ConstructedWetland,
    SepticSystem,
    CentralizedWWTP,
    DecentralizedWWTP,
    FlushToilet,
    DryToilet,
    Latrine,
    CompostingToilet,
    OpenField
)

WEFE_TYPEMAP = {
    "water-pump": WaterPump,
    "water-filtration": WaterFiltration,
    "crop": SimpleCrop,
    "mimo-crop": MimoCrop,
    "pv-panel": PVPanel,
    "mimo": MIMO,
    "apv": APV,
    "inverter": Inverter,
    "hydropower": RRHydropower,
    "river-flow": Volatile,
    "wind-turbine": WindTurbine,
    "reverse_osmosis": ReverseOsmosis,
    "ultrafiltration": UltraFiltration,
    "nanofiltration": NanoFiltration,
    "microfiltration": MicroFiltration,
    "biofiltration": BioFiltration,
    "activated_carbon_filter": ActivatedCarbonFilter,
    "ceramic_filter": CeramicFilter,
    "cartridge_filter": CartridgeFilter,
    "slow_sand_filter": SlowSandFilter,
    "electrodialysis": ElectrodialysisUnit,
    "ion_exchange": IonExchange,
    "uv_disinfection": UVDisinfection,
    "boiling": Boiling,
    "distillation": Distillation,
    "membrane_distillation": MembraneDistillation,
    "ozonation": Ozonation,
    "photocatalysis": PhotocatalyticUnit,
    "biological_denitrification": BiologicalDenitrification,
    "adsorption": Adsorption,
    "coagulation_flocculation": CoagulationFlocculation,
    "chlorination": Chlorination,
    "simple_oxidation": SimpleOxidation,
    "intake_structure": IntakeStructure,
    "coarse_bar_screen": CoarseBarScreen,
    "fine_screen": FineScreen,
    "grit_chamber": GritChamber,
    "water_reuse_system": WaterReuseSystem,
    "constructed_wetland": ConstructedWetland,
    "septic_system": SepticSystem,
    "centralized_WWTP": CentralizedWWTP,
    "decentralized_WWTP": DecentralizedWWTP,
    "flush_toilet": FlushToilet,
    "dry_toilet": DryToilet,
    "latrine": Latrine,
    "composting_toilet": CompostingToilet,
    "open_field": OpenField,
    "mimo_ro": MIMO_ReverseOsmosis,
    "mimo_uf": MIMO_UltraFiltration,
    "mimo_nf": MIMO_NanoFiltration,
    "mimo_mf": MIMO_MicroFiltration,
    "mimo_biof": MIMO_BioFiltration,
    "mimo_ix": MIMO_IonExchange,
    "mimo_ed": MIMO_Electrodialysis
}

WEFE_TYPEMAP.update(TYPEMAP)
