from oemof_tabular_plugins.wefe.constraints.constraint_facades import (
    CONSTRAINT_TYPE_MAP,
)
from oemof.tabular.facades import TYPEMAP

from oemof.tabular.facades import Volatile

from .facades import (
    PVPanel,
    WindTurbine,
    MIMO,
    APV,
    MimoCrop,
    SimpleCrop,
    WaterPump,
    WaterFiltration,
    Inverter,
    RRHydropower,
    ReverseOsmosis,
    UltraFiltration,
    NanoFiltration,
    MicroFiltration,
    BioFiltration,
    ActivatedCarbonFilter,
    CeramicFilter,
    CartridgeFilter,
    SlowSandFilter,
    ElectrodialysisUnit,
    IonExchange,
    UVDisinfection,
    Boiling,
    Distillation,
    MembraneDistillation,
    Ozonation,
    PhotocatalyticUnit,
    BiologicalDenitrification,
    Adsorption,
    CoagulationFlocculation,
    Chlorination,
    SimpleOxidation,
    IntakeStructure,
    CoarseBarScreen,
    FineScreen,
    GritChamber,
    WaterReuseSystem,
    ConstructedWetland,
    SepticSystem,
    CentralizedWWTP,
    DecentralizedWWTP,
    FlushToilet,
    DryToilet,
    Latrine,
    CompostingToilet,
    OpenField,
    MIMO_ReverseOsmosis,
    MIMO_UltraFiltration,
    MIMO_NanoFiltration,
    MIMO_MicroFiltration,
    MIMO_BioFiltration,
    MIMO_MembraneDistillation,
    MIMO_Distillation,
    MIMO_Electrodialysis,
    MIMO_IonExchange,
    MIMO_CartridgeFilter,
    MIMO_ActivatedCarbonFilter,
    MIMO_Chlorination,
    MIMO_CeramicFilter,
    MIMO_SlowSandFilter,
    MIMO_UVDisinfection,
    MIMO_Adsorption,
    MIMO_SimpleOxidation,
    MIMO_Ozonation,
    MIMO_Photocatalysis,
    MIMO_IntakeStructure,
    MIMO_CoarseBarScreen,
    MIMO_CoagulationFlocculation,
    MIMO_Boiling,
    MIMO_FineScreen,
    MIMO_GritChamber,
    MIMO_FlushToilet,
    MIMO_Latrine,
    MIMO_CompostingToilet,
    MIMO_DryToilet,
    MIMO_OpenField,
    MIMO_SepticSystem,
    MIMO_ConstructedWetland,
    MIMO_CentralizedWWTP,
    MIMO_DecentralizedWWTP,
    MIMO_WaterReuseSystem,
    MIMO_BiologicalDenitrification,
    WaterPreTreatment,
    WaterCoreTreatment,
    WaterPostTreatment
)

WEFE_TYPEMAP = {
    "water-pump": WaterPump,
    "water-filtration": WaterFiltration,
    "crop": SimpleCrop,
    "mimo-crop": MimoCrop,
    "pv-panel": PVPanel,
    "mimo": MIMO,
    "apv": APV,
    "inverter": Inverter,
    "hydropower": RRHydropower,
    "river-flow": Volatile,
    "wind-turbine": WindTurbine,
    "reverse_osmosis_3": ReverseOsmosis,
    "ultrafiltration_3": UltraFiltration,
    "nanofiltration_3": NanoFiltration,
    "microfiltration_3": MicroFiltration,
    "biofiltration_3": BioFiltration,
    "activated_carbon_filter_3": ActivatedCarbonFilter,
    "ceramic_filter_3": CeramicFilter,
    "cartridge_filter_3": CartridgeFilter,
    "slow_sand_filter_3": SlowSandFilter,
    "electrodialysis_3": ElectrodialysisUnit,
    "ion_exchange_3": IonExchange,
    "uv_disinfection_3": UVDisinfection,
    "boiling_3": Boiling,
    "distillation_3": Distillation,
    "membrane_distillation_3": MembraneDistillation,
    "ozonation_3": Ozonation,
    "photocatalysis_3": PhotocatalyticUnit,
    "biological_denitrification_3": BiologicalDenitrification,
    "adsorption_3": Adsorption,
    "coagulation_flocculation_3": CoagulationFlocculation,
    "chlorination_3": Chlorination,
    "simple_oxidation_3": SimpleOxidation,
    "intake_structure_3": IntakeStructure,
    "coarse_bar_screen_3": CoarseBarScreen,
    "fine_screen_3": FineScreen,
    "grit_chamber_3": GritChamber,
    "water_reuse_system_3": WaterReuseSystem,
    "constructed_wetland_3": ConstructedWetland,
    "septic_system_3": SepticSystem,
    "centralized_WWTP_3": CentralizedWWTP,
    "decentralized_WWTP_3": DecentralizedWWTP,
    "flush_toilet_3": FlushToilet,
    "dry_toilet_3": DryToilet,
    "latrine_3": Latrine,
    "composting_toilet_3": CompostingToilet,
    "open_field_3": OpenField,
    "mimo_ro": MIMO_ReverseOsmosis,
    "mimo_uf": MIMO_UltraFiltration,
    "mimo_nf": MIMO_NanoFiltration,
    "mimo_mf": MIMO_MicroFiltration,
    "mimo_biof": MIMO_BioFiltration,
    "mimo_ix": MIMO_IonExchange,
    "mimo_biological_denitrification": MIMO_BiologicalDenitrification,
    "mimo_ed": MIMO_Electrodialysis,
    "mimo_memb_dist": MIMO_MembraneDistillation,
    "mimo_dist": MIMO_Distillation,
    "mimo_cartridge_filter": MIMO_CartridgeFilter,
    "mimo_activated_carbon_filter": MIMO_ActivatedCarbonFilter,
    "mimo_chlor": MIMO_Chlorination,
    "mimo_ceramic_filter": MIMO_CeramicFilter,
    "mimo_slow_sand_filter": MIMO_SlowSandFilter,
    "mimo_uv": MIMO_UVDisinfection,
    "mimo_ads": MIMO_Adsorption,
    "mimo_simple_oxidation":MIMO_SimpleOxidation,
    "mimo_ozonation": MIMO_Ozonation,
    "mimo_photo_cat": MIMO_Photocatalysis,
    "mimo_intake_structure": MIMO_IntakeStructure,
    "mimo_coarse_bar_screen": MIMO_CoarseBarScreen,
    "mimo_coag_flocc": MIMO_CoagulationFlocculation,
    "mimo_boiling": MIMO_Boiling,
    "mimo_fine_screen": MIMO_FineScreen,
    "mimo_grit_chamber": MIMO_GritChamber,
    "mimo_flush_toilet": MIMO_FlushToilet,
    "mimo_latrine": MIMO_Latrine,
    "mimo_composting_toilet": MIMO_CompostingToilet,
    "mimo_dry_toile": MIMO_DryToilet,
    "mimo_open_field": MIMO_OpenField,
    "mimo_septic": MIMO_SepticSystem,
    "mimo_constructed_wetland": MIMO_ConstructedWetland,
    "mimo_centralized_WWTP": MIMO_CentralizedWWTP,
    "mimo_decentralized_WWTP": MIMO_DecentralizedWWTP,
    "mimo_water_reuse": MIMO_WaterReuseSystem,
    "water_pre_treatment_3": WaterPreTreatment,
    "water_core_treatment_3": WaterCoreTreatment,
    "water_post_treatment_3": WaterPostTreatment
}

WEFE_TYPEMAP.update(TYPEMAP)
